version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: frontend/scripts/before_install.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: frontend/scripts/after_install.sh
      timeout: 600
      runas: ec2-user

  ApplicationStart:
    - location: frontend/scripts/start_all.sh
      timeout: 600
      runas: ec2-user

  ApplicationStop:
    - location: frontend/scripts/stop_all.sh
      timeout: 300
      runas: ec2-user
